'use strict';

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


*/

(function(){
    function fib(n, sum=0, prev=1) {
        console.log(new Error().stack);
      if (n <= 1) return sum;
      return fib(n-1, prev+sum, sum);
    }
    console.log(fib(20000));
})();

// IT SEEMS TO BE THAT TCO IS NOT WORKING IN NODEJS

// https://bugs.chromium.org/p/v8/issues/detail?id=4698#c69
// https://www.reddit.com/r/node/comments/8qfhy0/what_happened_to_tco_tail_call_optimization_after/
